CREATE TABLE IF NOT EXISTS service(
    id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS car(
    id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS customer(
    id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS garage(
    id INT NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT
);

DELETE FROM service;
DELETE FROM garage;
DELETE FROM car;
DELETE FROM customer;